<?php

namespace AppBundle\Repository;

/**
 * CheckProvider
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CheckProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkProv()
    {

        $q=$this->getEntityManager()->createQuery("SELECT * FROM UserBundle:User  where roles='a:1:{i:0;s:13:\"ROLE_PROVIDER\";}'");
        return $query=$q->getResult();

    }
}
